services:
  rtsp:
    image: bluenviron/mediamtx:latest-ffmpeg
    # network_mode: host
    ports:
      - 8554:8554
    volumes:
      - ./media/sample.mp4:/sample.mp4
      - ./mediamtx.yml:/mediamtx.yml:ro