[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
futures-util = "0.3.31"
interpolation = "0.3.0"
tokio = { version = "1.44.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
